### ISSUE TITLE
Omporting Credentials

### ISSUE THREAD

**Issue by OzgunAras1** [ugis22/analysing_twitter#1]
#Importing postgres credentials
from postgres_credentials import *

#Importing twitter credentials
from twitter_credentials import *

what is for the code above? In my JupyterLab I get the error " No module named 'postgres_credentials' "

Thank you

**Comment by SurajMeena** [comment]
postgres_credentials is a python file which just contains the login details for connecting to postgres database

**Comment by ugis22** [comment]
Hello, sorry for not getting back to you before. Yes, postgres_credentials is a python file where you should store the credentials for you database. The same happens with twitter_credentials. Because they are secret, you shoul never publish them in GitHub

**Comment by Nowi5** [comment]
Please upload a example file, thank you.
