### ISSUE TITLE
Execution of delete rows not getting completed

### ISSUE THREAD

**Issue by SurajMeena** [ugis22/analysing_twitter#2]
I tried running this code, I have my postgres and twitter credentials in a seperate python....so I ran data streaming notebook and it worked fine without giving any errors...twitter extraction stopped when my connection broke...after that I used cleaning_db but when I run delete_rows function on my table....the cell keeps on running and it doesn't reach to it's completion...What can be the possible reason for this ?

**Comment by ugis22** [comment]
Does the code impact your database? I mean, do you get cells deleted? Is the number of rows of your database changing?

**Comment by SurajMeena** [comment]
actually no code related to sql is actually going to completion it justs keeps on running....Am I doing something wrong...I tried to check number of rows in database...and that code also just kept on running...I don't know much about sql...What do you think are possible reason for this ?

**Comment by ugis22** [comment]
@SurajMeena could you solve the issue?

**Comment by SurajMeena** [comment]
yes I have solved it...thanks for your time.
Thankyou
